#服务器设置
server:
  port: 8848
  servlet:
    context-path: /community
#spring设置
spring:
  thymeleaf:
    cache: false #thymeleaf缓存,开发是设置为false,运行时设置为true.因为开启缓存可以减低服务器压力,而开发时会有可能读取到网页没有刷新的旧数据,故开发时最好关闭该缓存
  datasource: #DataSourceProperties
    driver-class-name: com.mysql.cj.jdbc.Driver #连接驱动全限定类名
    #datasource的URL后面的参数. CharacterEncoding为编码格式, useSSL为安全连接是否启用, serverTimeZone为时区设定:该项不设定会报错
    url: jdbc:mysql:///community?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    username: root #数据源的登录名
    password: root #数据源的登录密码
    type: com.zaxxer.hikari.HikariDataSource #spring内置的一个线程池(在spring中内置的线程池中性能最高)
    hikari:
      maximum-pool-size: 15 #hiakri线程池中的最大线程数
      minimum-idle: 5 #线程池中的最小空闲线程数
      connection-timeout: 30000 #连接超时时间(单位:毫秒)
  mail: #spring mail导入
    host: smtp.163.com #email服务器地址
    port: 465 #email端口
    username: 18825612545@163.com #邮件账号
    password: mm12345678 #邮件密码
    protocol: smtps #邮件协议
  #redis配置
  redis:
    database: 0 #redis的数仓索引0~15
    host: localhost
    port: 6379

#mybaits的配置
mybatis:
  mapper-locations: classpath:mapper/*.xml #mybatis需要映射的xml文件位置
  type-aliases-package: com.honghuang.community.entity #别名需要扫描的包
  configuration:
    use-generated-keys: true #启用对自增长的键的支持
    map-underscore-to-camel-case: true #下划线与驼峰格式的自动转换设置


community:
  path:
    domain: http://localhost:8848
    upload: D:/work/data/upload


